### ISSUE TITLE
Unhandled error from cucumber

### ISSUE THREAD

**Issue by bsommardahl** [xolvio/chimp#441]
When I run my specs and there is any unexpected error (element not found, tabid doesn't exist, etc), I get an unfriendly error from the depths of cucumber:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: Cannot read property 'getFileName' of undefined
    at isFrameInCucumber 
```

It doesn't matter what kind of error is happening to cause it, the reported error is always the same.

#####  Used version

* Chimp: 0.39.3
* Node.js: 4.4.7
* Operation system: Linux Mint 17.3, OSX 10.11.4, and Windows 8.1 (Git-SCM Bash)

#####  Console / Log Output

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: Cannot read property 'getFileName' of undefined
    at isFrameInCucumber (/usr/local/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:9:23)
    at Array.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:15:9)
    at TraceModifier._modify (/usr/local/lib/node_modules/chimp/node_modules/stack-chain/stack-chain.js:44:32)
    at Function.prepareStackTrace (/usr/local/lib/node_modules/chimp/node_modules/stack-chain/stack-chain.js:119:25)
    at trackRejection (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:1066:32)
    at reject (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:1131:5)
    at deferred.reject (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/q/q.js:633:16)
    at run (/usr/local/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/chimp/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Try updating Node to 6.x

**Comment by alanning** [comment]
For reference, looks like there is an open issue on the cucumber repo too:  https://github.com/cucumber/cucumber-js/issues/610

**Comment by bsommardahl** [comment]
According to the issue in the cucumberjs repo, this issue is present in v1.2.1 but not in previous issues. Could we downgrade cucumberjs to 1.2.0 until the issue is fixed?

**Comment by alanning** [comment]
I don't know how to actually do it but that sounds like a great workaround for now.

**Comment by bsommardahl** [comment]
Here's a PR: https://github.com/xolvio/chimp/pull/442

**Comment by bsommardahl** [comment]
@samhatoum I upgraded to Node v6.3.1 and got the same error. I'm pretty sure the problem is coming from cucumberjs v1.2.1 only.

**Comment by samhatoum** [comment]
Perhaps you could use a previous version of Chimp (v0.38.0) that used v1.0.0

**Comment by bsommardahl** [comment]
@samhatoum That's a good idea. I will likely have my team do that. 

In the mean time, I just tried the version from #442 locally and my tests ran without issue!

**Comment by samhatoum** [comment]
oh that's great to know, I'll look into downgrading

Which version of node did you use when that worked?

**Comment by bsommardahl** [comment]
Working with chimp 0.38.0:
- Node 4.4.3 on Linux Mint 17.3
- Node 4.4.7 on Windows 8.1
- Node 4.4.7 on OSX 10.11.4

Fun fact, I was not able to install chimp@0.38.0 on Node 6.3.1 because of a module incompatibility.

Workaround achieved!

**Comment by yann-stepienik-cko** [comment]
@samhatoum  Issue in cucumber fixed in 1.2.2 
Just need to be updated ! hurayy

**Comment by 2hansen** [comment]
I am seeing the same issue with:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: Cannot read property 'getFileName' of undefined
    at isFrameInCucumber 
```
after upgrading to chimp 0.39.3.

Upgrading cucumber to 1.2.2 does not seem to resolve this.

**Comment by samhatoum** [comment]
Fix coming shortly. Thanks for being patient

**Comment by PierreCBSI** [comment]
seeing the issue with chimp 0.40.4
