### ISSUE TITLE
Extreme slowdown over time

### ISSUE THREAD

**Issue by timcosta** [xolvio/chimp#524]
#####  Expected behaviour
Tests should execute at a uniform pace in a reasonable period of time.

#####  Actual behaviour
Tests begin running quickly, but slow down to several seconds per step towards the end of the test run.

Example of slow step:
```    
this.Then(/^The page is (.+)$/i, function (arg1) {
        browser.waitForExist('.navbar', 5000);
        var path;
        if (/t(est)?\s?a(pp)?1/i.test(arg1)) path = /\/ta1/;
        if (/t(es(t)?)?\s?a(pp)?2/i.test(arg1)) path = /\/ta2/;
        if (/(login)/i.test(arg1)) path = /\/login/;
        expect(browser.getUrl()).toMatch(path);
    });
```

```
56 scenarios (56 passed)
836 steps (836 passed)
26m21.872s
```

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: `./node_modules/.bin/chimp`
* Chimp config file: None.
* Chimp: 
```
./node_modules/.bin/chimp -v
0.41.2
```
* Node.js: `6.9.1`
* Java: 
```
java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```
* Operation system: 
```
uname -v
Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64
``` 
OS X Sierra

#####  Console / Log Output
Nothing except for passing steps. it is simply extremely slow.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by tjsail33** [comment]
```
  ✔ Given I have visited Login


[22:31:23]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/elements"

[22:31:23]  DATA		{"using":"id","value":"username"}

[22:31:23]  RESULT		[{"ELEMENT":"984"}]

[22:31:24]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/element/984/clear"

[22:31:24]  DATA		{}

[22:31:24]  RESULT		null

[22:31:24]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/element/984/value"

[22:31:24]  DATA		{"value":["a","b","+","c","d","e","f","g","h","i","(18 more items)"]}

[22:31:25]  RESULT		null

[22:31:26]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/elements"

[22:31:26]  DATA		{"using":"id","value":"password"}

[22:31:26]  RESULT		[{"ELEMENT":"985"}]

[22:31:27]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/element/985/clear"

[22:31:27]  DATA		{}

[22:31:27]  RESULT		null

[22:31:27]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/element/985/value"

[22:31:27]  DATA		{"value":["m","y","p","a","s","s"]}

[22:31:28]  RESULT		null

[22:31:29]  COMMAND	POST 	 "/wd/hub/session/5c5ce142-d9c4-4dc6-a872-bf712439c8cc/keys"

[22:31:29]  DATA		{"value":[""]}

[22:31:29]  RESULT		null```

Note that it took six seconds for this single step to complete.

**Comment by samhatoum** [comment]
Can you please create a very simple repository demonstrating the issue? That way we can see if it's the test code or indeed Chimp & related tools

**Comment by lgandecki** [comment]
@tjsail33 replication could be helpful (maybe even try to prepare a simple test/feature file and copy it 100 times with different names - the ones at the end should basically take as much time as the first ones, obviously)

Another question - do you see a memory usage increase over time? by either chimp or meteor server?

**Comment by tjsail33** [comment]
Working on a reproduction case - code is occurring in is IP and cant be shared, so i'm doing it from scratch. may need a day or two.

**Comment by And-re** [comment]
@samhatoum @tjsail33 
I managed to reproduce that problem in this repo: https://github.com/And-re/chimp-issue

**Comment by tjsail33** [comment]
@And-re just made my day. Thanks.

**Comment by lgandecki** [comment]
So far we know that the version 0.31.0 works fast if you disable the screenshots. 
We've also tried updating meteor/promise in cucumberjs and sync-webdriverio to the newest stable version - according to the article @Sanjo suggested: https://sandstorm.io/news/2016-09-30-fiber-bomb-debugging-story?utm_source=nodeweekly&utm_medium=email

But it didn't really change anything (or the change was small but didn't fix the main issue). Will keep investigating tomorrow if time allows.

**Comment by lgandecki** [comment]
@tjsail33 Weird. We can't reproduce this anymore. Maybe one of the dependencies got updated and fixed this.  Can you check if doing rm -rf node_modules and then npm install fixes the problem for you?

**Comment by tjsail33** [comment]
@lgandecki both of our E2E CI runs today took the same amount of time as they have in the past - it's not looking resolved on my end. Still about 38m for my full test suite, even with the E2E tests broken up by functionality and run with separate tags to reset the slow down.

**Comment by lgandecki** [comment]
@tjsail33 if you clone the repo from and_re and follow the instruction there do you still have the problem?
Maybe your CI caches your npm packages, could you try rebuilding without cache?

**Comment by tjsail33** [comment]
![image](https://cloud.githubusercontent.com/assets/3916501/20352164/5618e02e-abe4-11e6-93af-5fe7d9a3ae7b.png)

Last few E2E runs, no cache involved. Ran a `yarn upgrade` this morning in hopes that bumping all of our deps and clearing the cache would fix it, but it doesnt seem to have worked. still seeing 35m+ run times.

**Comment by tjsail33** [comment]
Also FWIW the test repo is still slowing down for me. Did a fresh clone and install, and the first specs were instant, now theyre taking a few seconds

**Comment by lgandecki** [comment]
Alright! Thanks. We will get back on it and see what's happening :)

**Comment by andrialexandrou** [comment]
So I'm running into a similar scenario, thought I might contribute my two cents. Similar situation - first tests run in ~5 seconds, but after a few scenarios it's ballooning out to ~25 seconds and more. On a colleague's machine, our ~130 tests take 60-90 minutes to run, usually closer to 90 minutes.

Made an estimation that it was something accumulating per scenario, so I just did some quick tracking and it looks like on the (global-ish?) object that persists throughout the tests, `browser`, `driver`, and `client` become pretty massive pretty quick. They're also identical in size, so I wonder if there's some unnecessary duping going on. For quick ref: 
(I'm looping over the context object and doing a quick `sizeof( this[ key] )` for quick look at size.)
```
Size of this context within after hook:  85646
browser		 28128
driver		 28128
client		 28128
request		 0
ddp		 0
mirror		 0
server		 0
chimpWidgets		 0
accountUrl		 68
users		 226
session		 78
boards		 60
cards		 0
currentBoardId		 0
createCard		 0
requireBoard		 0
requireAccountType		 0
isLegacy		 0
enums		 152
dataCleanup		 132
ids		 0
accountType		 22
timer		 8
toolbar		 32
home		 96
```
^ After First Scenario

And then after about 6 scenarios:
```
Size of this context within after hook:  396284
browser		 131654
driver		 131654
client		 131654
.
.
.
```
The other sizes remain about the same.

Before long, that number gets into the megabytes.

Starting to dig some source code, but thought I'd toss up a few breadcrumbs in case it helps.

**Comment by lgandecki** [comment]
That should be helpful! Thanks! 
Also, those are links to the same object :) so no worry there
https://github.com/xolvio/chimp/blob/master/src/lib/cucumberjs/world.js#L9

**Comment by andrialexandrou** [comment]
Ah ha, so then the sum size is actually going to be ab 1/3 of what it's reporting. Still, it grows pretty massively there. When we do `browser.whatever( arg )` in our step definitions does that store something on the browser object?

**Comment by lgandecki** [comment]
would you possibly be able to print one of those bigger objects? and paste it somewhere like https://gist.github.com/?

That is an excellent catch though! Very probably you found the cause. Weird that we couldn't reproduce it starting at some point.. We might have fixed it in one of the dependencies and forgot to unlink..

**Comment by andrialexandrou** [comment]
[Here's the big object w/ some silly sanitized information in it](https://gist.github.com/andrialexandrou/b8edeb5b670a2060fca3d98326d2ca77)

**Comment by andrialexandrou** [comment]
Tried a hack job of a workaround just clearing out that object every time, the `commandList` array, but it still seems to be accumulating some cruft somewhere.

**Comment by usmanchoudhary** [comment]
Morning all,

I am getting into similar issues, I've not used chimp.js before but is creating a negative perception for the business. Our test suite takes over an hour to execute. any help would be appreciated.
64 Scenario took 1h 5m 12s 065ms to complete.
Thank you

**Comment by workflow** [comment]
Guys, any update on this? This is making chimp unusable, and increasing the number of flickers we're seeing exponentially.

Thank you!

**Comment by lgandecki** [comment]
@workflow could you please check whether you see the problem in this repo: 
https://github.com/And-re/chimp-issue ? Last time I checked I couldn't reproduce it anymore. It will be a helpful information, maybe we need to try to find a different reproduction, or maybe there is something different about our machines (but I believe one of my guys tried it on a clean linux vm ..)

**Comment by workflow** [comment]
Yes! Fortunately I can reproduce it, with pretty much the exact same timings. (peak: ~11 seconds for a feature up from <1s)

That's on an Ubuntu 14.04 physical box, running
```
node: 6.9.1 (npm 3.10.8)
chrome: Version 55.0.2883.75 (64-bit)
```

Happy to share more data about the machine. Any gut feeling?

**Comment by lgandecki** [comment]
Thanks a lot! I will have a pair working on this starting today.. we will give you update by the end of the day

**Comment by lucetius** [comment]
@workflow check with node 6.3.1

**Comment by workflow** [comment]
http://s2.quickmeme.com/img/93/93ae4baa31e98be52e9f2b325a3e19b3753e7ffdfc5517bcb7264659435119e0.jpg

**Comment by lgandecki** [comment]
This is obviously not a good long-term solution. We don't really understand what's causing the slowdown yet :( 
Profiling didn't prove very helpful yet. Looks like the problem starts at 6.5.0

**Comment by samhatoum** [comment]
Just as a hunch, could it perhaps be a fibers <> new node issue?

**Comment by tjsail33** [comment]
@lgandecki any luck on this issue yet?

**Comment by And-re** [comment]
I was investigating this issue today and there might be some problem with meteor-promise package:
https://github.com/meteor/promise/issues/14#issuecomment-273206068

**Comment by woutervandergraaf** [comment]
Tried that testing repository of @And-re in Node 6.9 and the slowdown is very noticable. Now I'm running it on Node 6.4 and WOW! The speed difference is huge, even in the beginning of the test run. Would love to see this fixed.

**Comment by tiagolr** [comment]
Confirmed, using node 6.10 was getting tests awfully slow, thanks for posting this.

**Comment by Sanjo** [comment]
If it is a Fibers issue, this optimizations might help:
* Use Promise.async(..., true) for https://github.com/xolvio/chimp/blob/master/src/lib/utils/fiberize.js from the [meteor-promise package](https://github.com/meteor/promise/blob/master/promise_server.js#L91-L101). This will reuse Fibers.
*  Pass `true` as second argument to the calls to Promise.async to reuse Fibers instead of creating new ones. Packages: chimp, sync-webdriverio and cucumber fork

**Comment by viditm** [comment]
After the latest update to Chrome (from 56 to 57) I was forced to update to a newer version of chimp due to selenium webdriver and now get this same slowdown with the following setup.
Node: 4.5.0
Chimp: 0.46.0

Going to node 6.4 does not improve my speeds at all so this seems like something that will become more critical in the near future.

**Comment by corwin-of-amber** [comment]
I think I have a lead on this and it seems that this issue is active so I want to contribute my experience. Over the last three days I was trying to use meteor-promise with node 7.0.0 and noticing that my server process consumes 100% CPU while just waiting for a connection. I profiled it a bit and was surprised to find out that ```wrapCallback``` is being called non-stop. I managed to reduce it to a minimal code snippet:

```javascript
f = require('fibers');
require('meteor-promise').makeCompatible(Promise, f);

new Promise(function(r) { r() }).then(function() {});
```

This process never terminates, but goes into an infinite callback loop. I edited ```promise_server.js``` and added a printf in ```wrapCallback```:

```javascript
function wrapCallback(callback, Promise, dynamics) {
  console.log("[promise] wrapCallback", callback);
  ...
```

Sure enough, the output is:
```
[promise] makeCompatible function then() { [native code] }
[promise] wrapCallback function () {}
[promise] wrapCallback undefined
[promise] wrapCallback function t() { [native code] }
[promise] wrapCallback function u() { [native code] }
[promise] wrapCallback function t() { [native code] }
[promise] wrapCallback function u() { [native code] }
[promise] wrapCallback function t() { [native code] }
[promise] wrapCallback function u() { [native code] }
[promise] wrapCallback function t() { [native code] }
[promise] wrapCallback function u() { [native code] }
[promise] wrapCallback function t() { [native code] }
[promise] wrapCallback function u() { [native code] }
[promise] wrapCallback function t() { [native code] }
.
.
.
```

I was wondering forever what these functions ```t``` and ```u``` were. In case you are also wondering:
```
% node
> new Promise((a,b) => { console.log(a.toString(), b.toString()); })
function t() { [native code] } function u() { [native code] }
Promise { <pending> }
>
```

I think they are the ones created in ```FiberPool.run``` (```fiber_pool.js```):
```javascript
    var promise = new Promise(function (resolve, reject) {
      entry.resolve = resolve;
      entry.reject = reject;
    });
```

But I am not entirely sure how they end up as arguments to ```wrapCallback```, but it seems that Node.js started queueing promise resolve and reject hooks as microtasks and these in turned are implemented by calling ```Promise.then``` again. Still investigating this so I may come up with a more complete explanation.

**Comment by tiagolr** [comment]
Any progress on this? Still using node 4.8.0 because of this

**Comment by corwin-of-amber** [comment]
@benjamn (who is maintaining github.com/meteor/promise) was very responsive and we were able to fix the problem with the promise package that was causing the problem. Specifically, [this changeset](https://github.com/meteor/promise/commit/fe13621337fab866839f28fa8dd8c7d8fa82a486) solved the high CPU issue. By now, it is published as version 0.8.2 of meteor-promise; I don't know how to use this information to make it propagate to the meteor distribution though... my temporary solution was to clone the meteor source repository, then forcefully overwrite ```promise_server.js``` across the code base (it is duplicated about five times) using something of the form:
```bash
cd your/meteor/source/directory
npm install meteor-promise
for i in `find . -name 'promise_server.js'` ; do 
  cp node_modules/meteor-promise/promise_server.js $i
done
```

Pretty sure there is a better way.

**Comment by tiagolr** [comment]
Thank you! Would be nice to see this this update in upcomming chimp versions, btw great work @chimpteam with 0.48.0 version fixing json output issues.

**Comment by schovi** [comment]
Same issue there. Having 22 Scenarios with about 200 steps and it tooks around 20 minutes. Each step separately takes max 10 seconds. Using latest Node 6.10.3, bacause 7 failing sometime with `TypeError: Cannot read property 'trim' of undefined` and less than 6 can't be used because of new syntax using there. 

Can I try something to debug problem?

**Comment by schovi** [comment]
Same issue there. Having 22 Scenarios with about 200 steps and it tooks around 20 minutes. Each step separately takes max 10 seconds. Using latest Node 6.10.3, bacause 7 failing sometime with `TypeError: Cannot read property 'trim' of undefined` and less than 6 can't be used because of new syntax using there. 

Chimp 0.48.0

Can I try something to debug problem?

**Comment by lgandecki** [comment]
Hey guys, I believe this is finally fixed with the version I just released 0.49.0 . I tested it on v7.9.0 node. Switching back to 0.48.0 makes it slow again. Please update and confirm.

The meteor-promise turned out to indeed be the culprit, I had to update cucumber-js and sync-webdriverio accordingly. 

Thanks @corwin-of-amber @benjamn @Sanjo @And-re @lucetius @andrialexandrou @samhatoum  for help with debugging, and @tiagolr @schovi @viditm @woutervandergraaf @timcosta @workflow  for reporting and providing with details. ( I hope I haven't missed anyone )
Phew! This took as long enough!

**Comment by schovi** [comment]
@lgandecki 
1) Node 7.10 and still gets one `TypeError: Cannot read property 'trim' of undefined` error
2) About speed it is awesome! It took 1/4 time than before.
Totally progress! :)

**Comment by schovi** [comment]
@lgandecki After resolving some new errors we deployed it to CI and time went from 30 minutes to just 2,5 (including some minor tests optimizations)

**Comment by benjamn** [comment]
It's great to hear this issue seems to be resolved! As the maintainer of the `meteor-promise` package, I would humbly
1. apologize for the unfortunate interaction between that package and Node 6+, and
2. mention that the latest version of `meteor-promise` (0.8.4) not only fixes these problems itself but also eliminates the problem from any other (older) copies of `meteor-promise` that might be accidentally in use.
