### ISSUE TITLE
Why not pin the package chromedriver?

### ISSUE THREAD

**Issue by SimonSimCity** [xolvio/chimp#666]
As of today, the Chromedriver binary, installed by this package is pinned to v2.28:
https://github.com/xolvio/chimp/blob/8fe398ef16d87fa127096223df0c2944b7390f00/src/bin/default.js#L66-L80

Was there a reason then not to pin the npm-package chromedriver?
https://github.com/xolvio/chimp/blob/8fe398ef16d87fa127096223df0c2944b7390f00/package.json#L85

Since this version isn't pinned, but loads the binary as well, I thought I was installing the latest binary, which led me to filing this bug-report: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2141

Later on I had to paddle back and to concede, that I actually used a totally different version of the chromedriver than what I expected.

Wouldn't it make much more sense to pin the version of the npm-package `chromedriver`, as the binary for `selenium-standalone` is pinned?

**Comment by honzajavorek** [comment]
The package.json entry could be pinned, and the `chimp/src/bin/default.js` file could take the value from there: `require('./package').dependencies.chromedriver`

**Comment by samhatoum** [comment]
@SimonSimCity thank you for the PR. I just fixed this in an upcoming commit

@honzajavorek I just did your suggestion for Chrome driver. Thank you :)

**Comment by SimonSimCity** [comment]
@samhatoum, I've looked at the code in e7982ca00155256e2e029586906ce39e1f5b5a47 and I sadly have to disagree with the solution you chose. It does not fix this issue and might even make it harder to understand. It only solves that the maintainer of this package doesn't have to update the one number when updating the other, but your solution could (again) lead to a situation where NPM installs `chromedriver` in version `2.50.0` but the downloaded package for `selenium-standalone` would still be `2.34`. This is (in my eyes) even more confusing because it seems to use the exact same version as defined in the `package.json` configuration until you read about the difference of the caret [`^`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) and the tilde [`~`](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) in the [`semver`](https://docs.npmjs.com/misc/semver) package. A caret allows all but the first non-zero number to change, which includes the minor and bugfix version. Whereby the tilde only allows the bugfix number to change. Please read the linked docs for further explanation.

Please do one of the following:

* Either change the caret [`^`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) to a tilde [`~`](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1). 
* Or pin it to the exact version, like I did: https://github.com/xolvio/chimp/pull/670/commits/09e2ecd46788a10497709e622cc9b8ffb0b7f7d1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R85

I'd be happy to see this solved correctly 😉

**Comment by samhatoum** [comment]
Totally makes sense @SimonSimCity. I'm changing to a ~.

**Comment by samhatoum** [comment]
released in 0.51.0

**Comment by samhatoum** [comment]
Thanks again @SimonSimCity
